// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using skillsync.api.Data;

#nullable disable

namespace skillsync.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("skillsync.api.Models.CareerGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerGoalsId")
                        .HasColumnType("integer");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CareerGoalsId");

                    b.ToTable("CareerGoal");
                });

            modelBuilder.Entity("skillsync.api.Models.CareerGoals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkPreference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CareerGoals");
                });

            modelBuilder.Entity("skillsync.api.Models.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("skillsync.api.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer");

                    b.Property<string>("HighestEducation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Education");
                });

            modelBuilder.Entity("skillsync.api.Models.JobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkExperienceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkExperienceId");

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("skillsync.api.Models.PersonalDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("skillsync.api.Models.PreferredIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerGoalsId")
                        .HasColumnType("integer");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CareerGoalsId");

                    b.ToTable("PreferredIndustry");
                });

            modelBuilder.Entity("skillsync.api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SkillsId")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillsId1")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillsId2")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillsId3")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillsId");

                    b.HasIndex("SkillsId1");

                    b.HasIndex("SkillsId2");

                    b.HasIndex("SkillsId3");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("skillsync.api.Models.Skills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("skillsync.api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgreeToTerms")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("skillsync.api.Models.WorkExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("WorkExperience");
                });

            modelBuilder.Entity("skillsync.api.Models.CareerGoal", b =>
                {
                    b.HasOne("skillsync.api.Models.CareerGoals", "CareerGoals")
                        .WithMany("Goals")
                        .HasForeignKey("CareerGoalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerGoals");
                });

            modelBuilder.Entity("skillsync.api.Models.CareerGoals", b =>
                {
                    b.HasOne("skillsync.api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("skillsync.api.Models.CareerGoals", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("skillsync.api.Models.Certification", b =>
                {
                    b.HasOne("skillsync.api.Models.Education", "Education")
                        .WithMany("Certifications")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");
                });

            modelBuilder.Entity("skillsync.api.Models.Education", b =>
                {
                    b.HasOne("skillsync.api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("skillsync.api.Models.Education", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("skillsync.api.Models.JobRole", b =>
                {
                    b.HasOne("skillsync.api.Models.WorkExperience", "WorkExperience")
                        .WithMany("JobRoles")
                        .HasForeignKey("WorkExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkExperience");
                });

            modelBuilder.Entity("skillsync.api.Models.PersonalDetails", b =>
                {
                    b.HasOne("skillsync.api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("skillsync.api.Models.PersonalDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("skillsync.api.Models.PreferredIndustry", b =>
                {
                    b.HasOne("skillsync.api.Models.CareerGoals", "CareerGoals")
                        .WithMany("PreferredIndustries")
                        .HasForeignKey("CareerGoalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerGoals");
                });

            modelBuilder.Entity("skillsync.api.Models.Skill", b =>
                {
                    b.HasOne("skillsync.api.Models.Skills", "Skills")
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("skillsync.api.Models.Skills", null)
                        .WithMany("SkillsToLearn")
                        .HasForeignKey("SkillsId1");

                    b.HasOne("skillsync.api.Models.Skills", null)
                        .WithMany("SoftSkills")
                        .HasForeignKey("SkillsId2");

                    b.HasOne("skillsync.api.Models.Skills", null)
                        .WithMany("TechnicalSkills")
                        .HasForeignKey("SkillsId3");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("skillsync.api.Models.Skills", b =>
                {
                    b.HasOne("skillsync.api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("skillsync.api.Models.Skills", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("skillsync.api.Models.WorkExperience", b =>
                {
                    b.HasOne("skillsync.api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("skillsync.api.Models.WorkExperience", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("skillsync.api.Models.CareerGoals", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("PreferredIndustries");
                });

            modelBuilder.Entity("skillsync.api.Models.Education", b =>
                {
                    b.Navigation("Certifications");
                });

            modelBuilder.Entity("skillsync.api.Models.Skills", b =>
                {
                    b.Navigation("SkillsToLearn");

                    b.Navigation("SoftSkills");

                    b.Navigation("TechnicalSkills");
                });

            modelBuilder.Entity("skillsync.api.Models.WorkExperience", b =>
                {
                    b.Navigation("JobRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
